# Generated by Django 4.2.5 on 2023-09-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_warehouse_created_by'),
        ('products', '0002_product_user_alter_barcode_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ManyToManyField(to='store.warehouse'),
        ),
    ]
