# Generated by Django 4.2.5 on 2023-09-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_warehouse_created_by'),
        ('products', '0003_alter_product_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ManyToManyField(related_name='product_warehouses', to='store.warehouse'),
        ),
    ]
