# Generated by Django 4.2.5 on 2023-09-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_warehouse_created_by'),
        ('products', '0004_alter_product_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ManyToManyField(to='store.warehouse'),
        ),
    ]
