# Generated by Django 4.2.5 on 2023-09-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_featured_alter_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode-image/'),
        ),
    ]
