# Generated by Django 4.2.5 on 2023-09-18 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_warehouse_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_biller_created_by_alter_customer_created_by_and_more'),
        ('products', '0007_alter_product_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('sales_tax', models.CharField(choices=[('8', 'Vat @8%'), ('9', 'Vat @9%'), ('10', 'Vat @10%'), ('11', 'Vat @11%'), ('12', 'Vat @12%'), ('13', 'Vat @13%')], max_length=10)),
                ('discount', models.FloatField()),
                ('shipping', models.FloatField()),
                ('sales_status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Drafts', 'Drafts')], max_length=15)),
                ('payment_status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Drafts', 'Drafts')], max_length=15)),
                ('sales_image', models.ImageField(blank=True, null=True, upload_to='sales/')),
                ('sales_note', models.TextField()),
                ('staff_remark', models.TextField()),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_biller', to='accounts.biller')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_customer', to='accounts.customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_warehouse', to='store.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('order_tax', models.CharField(choices=[('8', 'Vat @8%'), ('9', 'Vat @9%'), ('10', 'Vat @10%'), ('11', 'Vat @11%'), ('12', 'Vat @12%'), ('13', 'Vat @13%')], max_length=10)),
                ('order_discount', models.FloatField()),
                ('shipping', models.FloatField()),
                ('sales_status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Drafts', 'Drafts')], max_length=15)),
                ('purchase_note', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_supplier', to='accounts.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_warehouse', to='store.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
