# Generated by Django 4.2.5 on 2023-09-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='product',
        ),
        migrations.AddField(
            model_name='adjustment',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
