# Generated by Django 4.2.5 on 2023-09-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_adjustment_product_adjustment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
