# Generated by Django 4.2.5 on 2023-09-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_adjustment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='type',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Substraction', 'Substraction')], default='Addition', max_length=15),
        ),
    ]
