# Generated by Django 4.2.5 on 2023-09-20 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_biller_created_by_alter_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
