# Generated by Django 4.2.5 on 2023-09-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_supplier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Superadmin', 'Superadmin'), ('Supervisor', 'Supervisor'), ('Biller', 'Biller'), ('Staff', 'Staff'), ('Supplier', 'Supplier'), ('Customer', 'Customer')], max_length=20, null=True),
        ),
    ]
