# Generated by Django 4.2.5 on 2023-10-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_author_blog_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='number_of_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='number_of_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
    ]
